#ifndef BZ_VERSION_H
#define BZ_VERSION_H
/* Normally generated by bzip2's build; vendored here. Version string only —
 * consumed by BZ2_bzlibVersion() in bzlib.c. */
#define BZ_VERSION "1.0.8"
#endif
